version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
